### PR TITLE
Add ERD for our app

### PR DESCRIPTION
**Pull request by thetaxas2468**
In this commit we have added our ERD.

### CODE REVIEW

**Comment by Omeramsc** [comment]
I'm not sure why the old PR got closed? just like code, we expect to see changes on the same PR.

**Comment by Omeramsc** [comment]
Some of my old comments still applies:
- Why does the Supplier have a password, but it lacks a username?
- You set delivering area for Supplier as a string. is there only one delivering area per Supplier?
- Isn't the Supplier and the Client both Users in the system?
- I see the cart contains a qr_code foreign key, can a cart include only one item?

**Comment by Omeramsc** [comment]
(sorry for the spam) - I can't help but feel the ERD is missing something. it looks like a system that allows clients to order items from suppliers, which is ok, but isn't the main point of the project a large social *group* buy?  it seems very personal and not very social.

**Comment by nofaralfasi** [comment]
If I understand correctly, you are trying to save the cart's items for each client in the Item_Cart table (again, I don't think it is the right approach). 
But what will happen after the user paid for these items? Will you delete them from the database? Will you add a `status` field and then go over all the relevant items and filter them by their status? 

Also, why do you need the FK for the Product table, and the FK for the Supplier table? Why not use instead a FK for the Product_Supplier table?

**Comment by thetaxas2468** [comment]
@Omeramsc 
-Supplier is something the admin create,password is set by admin too that each supplier need to know sup_id and his password and clients and suppliers has their own urls to access
-yes each supplier is for one delivering area
-a cart can contain many items
-yes they both users but one is set by the admin of the site(not every 1 can be a supplier)

**Comment by thetaxas2468** [comment]
@nofaralfasi 
- After the client pay for the items we will delete each row that has the username that paid the items for him
- Django doesnt support multiple fields to be primary key,our Foreign Keys is also going to be primary by the design we are going to make and by the ERD we cant just save a one product_supplier to because its a row for a supplier with a specific product and not all the catalog for the supplier

**Comment by Omeramsc** [comment]
> @Omeramsc -Supplier is something the admin create,password is set by admin too that each supplier need to know sup_id and his password and clients and suppliers has their own urls to access -yes each supplier is for one delivering area -a cart can contain many items -yes they both users but one is set by the admin of the site(not every 1 can be a supplier)

- If a cart can contain multiple items, the ERD does not portray it. you cannot have multiple instances of the same field or one field that contain multiple objects. the solution for this is another table to represent the connection\relationship between the entities. e.g: "items in cart", containing an item FK and a cart FK. then, when you need this information you ask the DB for all "items in cart" with the cart FK. 
- They're still both users, and they have similar fields. I think they should derive from the same user entity. Also, you're mentioning an admin here, how will you implement his privileges? he might also be an entity or at least a variable.

**Comment by MeitarRizner** [comment]
I'm not sure about the arrow between Supplier and item_in_delivery - how zero supplier can have one or many Item_in_delivery? I think the arrow might be one and only supplier to one(or zero?) or many item_in_delivery.

In addition i'm not sure about these arrows:
Arrow between supplier to product_for_supplier - each supplier have one or many products. So the arrow might be one and only supplier to zero or many products.

Arrow between item_in_delivery to productr_for_supplier - might be one or many item to one or many products. Item can have 0 products?

Arrow between product to productr_for_supplier -  might be one product to zero or many productr_for_supplier.

Apart from these things you did a great job!

**Comment by Omeramsc** [comment]
- I know it seems like nitpicking, but please keep the lines straight, and try to assure they're not crossing each other. it affects readability heavily.
- User has a password but does not have a username? how?
- I don't really get the `money` part under client. does he charge money into the account? wouldn't it be easier if he would just pay for the items when purchasing them?
- Can a delivery really have zero-to-many items in delivery? why make a delivery with zero items?
- There is no such thing as 3 fields that are only unique together. each field is independent (also please remove the small comments beneath each class, it's distracting and not clear).
- I don't think there can be a `product_for_supplier` (which is really items in supplier's catalog) with 0 products, meaning each product in catalog can have one product only (one-to-one)
- We kinda created the names of the classes on the spot during our meeting, please refine them.

**Comment by nofaralfasi** [comment]
I agree with @Omeramsc, the ERD will look much clearer if you keep the lines short and straight.
Also, do we want to limit the client to only one area, as mentioned in the ERD? I'm thinking maybe it is unnecessary to declare the area field.
Not all fields have their type specified (like `first_name` and `last_name` in the `User` table).

**Comment by Omeramsc** [comment]
@nofaralfasi about the last point - I agree overall, but also think that a supplier can have 0 products for suppliers, for example - a new supplier in the system. or - a supplier that sold everything.

**Comment by pazMenachem** [comment]
> * User has a password but does not have a username? how?
> * Can a delivery really have zero-to-many items in delivery? why make a delivery with zero items?
> * There is no such thing as 3 fields that are only unique together. each field is independent (also please remove the small comments beneath each class, it's distracting and not clear).
> * I don't think there can be a `product_for_supplier` (which is really items in supplier's catalog) with 0 products, meaning each product in catalog can have one product only (one-to-one)
> * We kinda created the names of the classes on the spot during our meeting, please refine them.

1. is it possible that client and supplier (which inherit from User who has user_name as PK) will have also user_name as PK? 
2. yes, each delivery id could have zero or many products that were ordered to a certain area (delivery).
3. isnt composite unique key is a django feature?
4. modified

> 1. I agree with @Omeramsc, the ERD will look much clearer if you keep the lines short and straight.
> 2. Also, do we want to limit the client to only one area, as mentioned in the ERD? I'm thinking maybe it is unnecessary to declare the area field.
> 3. Not all fields have their type specified (like `first_name` and `last_name` in the `User` table).
> 4. I think the connection between `supplier` and `product_for_supplier` should be one-to-many, meaning that each `supplier` has many `product_for_supplier` (more accurate, at least one), and each `product_for_supplier` has exactly one `supplier`.

1.  modified.
2.  for now we will limit the area for each client.
3. modified.
4. modified.

**Comment by thetaxas2468** [comment]
Me and paz has looked and modified the erd with some changes
Delivery -> Delivery_location
Item in delivery - > Ordered_product
Product for supplier -> supplier_product

There is no such thing as 3 fields that are only unique together. each field is independen

each field is yes independent but we can create a unique together fields like
username for supplier and location for the supplier that he can deliver to

sup 1,location a
sup 1,location a (is a duplicate so we need one and only one)
sup 1,location b
.
.
.

**Comment by yftacherzog** [comment]
What's the purpose of the user's `type` field? `bool` is not very typical for types.

**Comment by Omeramsc** [comment]
> > * User has a password but does not have a username? how?
> > * Can a delivery really have zero-to-many items in delivery? why make a delivery with zero items?
> > * There is no such thing as 3 fields that are only unique together. each field is independent (also please remove the small comments beneath each class, it's distracting and not clear).
> > * I don't think there can be a `product_for_supplier` (which is really items in supplier's catalog) with 0 products, meaning each product in catalog can have one product only (one-to-one)
> > * We kinda created the names of the classes on the spot during our meeting, please refine them.
> 
> 1. is it possible that client and supplier (which inherit from User who has user_name as PK) will have also user_name as PK?
> 2. yes, each delivery id could have zero or many products that were ordered to a certain area (delivery).
> 3. isnt composite unique key is a django feature?
> 4. modified


1. WDYM? they don't need to have user names, just the user entity should have it. when I last looked, I didn't see it has it.
2. how do zero items make sense?
3. Not that I know, but maybe I'll learn something new :)

**Comment by Omeramsc** [comment]
> each field is yes independent but we can create a unique together fields like username for supplier and location for the supplier that he can deliver to
> 
> sup 1,location a sup 1,location a (is a duplicate so we need one and only one) sup 1,location b

The supplier should have an ID as its primary key. you'll never have two suppliers with the same ID as it is auto-generated, therefor such a situation will never occur.

**Comment by nofaralfasi** [comment]
1. Please change `Date` to `date` on the `Delivery_location` table. If you decided to use sentence case, you should stick to it. The same goes for `supplier_product`.
2. `Ordered product` is missing an underscore.
3. On the `User` table - `user_name` doesn't have the same mark as other PKs on the diagram.
4. On the `supplier_product` table the `quantity` field is missing a type.
5. I personally preferred the name `Delivery` for the table, more than `Delivery_location`. But if I'm the only one with that opinion then don't change it.
6. How can a `supplier_product` have 0 products?
7. A product can have only one `supplier_product` connected to it? Meaning that 2 suppliers can't sell the same product?

**Comment by LiorSilberman** [comment]
> What's the purpose of the user's `type` field? `bool` is not very typical for types.

The User class is abstract class, so the type field mean that if type equal to 0 so its meant to client and if its 1 its supplier.
I think we can change it from 'type' to 'access' or some word like this to make it more clear. and it still will be bool field.

**Comment by yftacherzog** [comment]
> > What's the purpose of the user's `type` field? `bool` is not very typical for types.
> 
> The User class is abstract class, so the type field mean that if type equal to 0 so its meant to client and if its 1 its supplier. I think we can change it from 'type' to 'access' or some word like this to make it more clear. and it still will be bool field.

Can be less cryptic about it. E.g. Make it a string or some sort of enumeration class and call it `user_type`. No?

**Comment by LiorSilberman** [comment]
> 

@thetaxas2468 I think we should change it to what Yftach said. In User class => change field 'type' to 'user_type' and make it Integer.

**Comment by yftacherzog** [comment]
> > 
> 
> @thetaxas2468 I think we should change it to what Yftach said. In User class => change field 'type' to 'user_type' and make it Integer.

why integer?

**Comment by LiorSilberman** [comment]
> > @thetaxas2468 I think we should change it to what Yftach said. In User class => change field 'type' to 'user_type' and make it Integer.
> 
> why integer?

I thought that this is what you meant by saying enumeration class.

0-client
1-supplier

maybe I didn’t understand you right

**Comment by yftacherzog** [comment]
> > > @thetaxas2468 I think we should change it to what Yftach said. In User class => change field 'type' to 'user_type' and make it Integer.
> > 
> > 
> > why integer?
> 
> I thought that this is what you meant by saying enumeration class.
> 
> 0-client 1-supplier
> 
> maybe I didn’t understand you right

ok. Just don't want it to be some sort of magic number or magic bool.

I think it can be of type `Enum`. Something like:

```python
In [39]: from enum import Enum
...
In [41]: class UserType(Enum):
    ...:     CLIENT = 1
    ...:     SUPPLIER = 2
    ...: 

In [42]: user_type = UserType.CLIENT

In [43]: user_type
Out[43]: <UserType.CLIENT: 1>

In [44]: user_type.name
Out[44]: 'CLIENT'

In [45]: user_type.value
Out[45]: 1
```

**Comment by yftacherzog** [comment]
> > > @thetaxas2468 I think we should change it to what Yftach said. In User class => change field 'type' to 'user_type' and make it Integer.
> > 
> > 
> > why integer?
> 
> I thought that this is what you meant by saying enumeration class.
> 
> 0-client 1-supplier
> 
> maybe I didn’t understand you right

ok. Just don't want it to be some sort of magic number or magic bool.

I think it can be of type `Enum`. Something like:

```python
In [39]: from enum import Enum
...
In [41]: class UserType(Enum):
    ...:     CLIENT = 1
    ...:     SUPPLIER = 2
    ...: 

In [42]: user_type = UserType.CLIENT

In [43]: user_type
Out[43]: <UserType.CLIENT: 1>

In [44]: user_type.name
Out[44]: 'CLIENT'

In [45]: user_type.value
Out[45]: 1
```

The downside of having this as enum is that we couple the abstract parent class with its implementations.

In any case, don't leave it as magic numbers/booleans.

**Comment by thetaxas2468** [comment]
> > > What's the purpose of the user's `type` field? `bool` is not very typical for types.
> > 
> > 
> > The User class is abstract class, so the type field mean that if type equal to 0 so its meant to client and if its 1 its supplier. I think we can change it from 'type' to 'access' or some word like this to make it more clear. and it still will be bool field.
> 
> Can be less cryptic about it. E.g. Make it a string or some sort of enumeration class and call it `user_type`. No?

I have changed it to str (either "user" or "supplier")

**Comment by thetaxas2468** [comment]
> 1. Please change `Date` to `date` on the `Delivery_location` table. If you decided to use sentence case, you should stick to it. The same goes for `supplier_product`.
> 2. `Ordered product` is missing an underscore.
> 3. On the `User` table - `user_name` doesn't have the same mark as other PKs on the diagram.
> 4. On the `supplier_product` table the `quantity` field is missing a type.
> 5. I personally preferred the name `Delivery` for the table, more than `Delivery_location`. But if I'm the only one with that opinion then don't change it.
> 6. How can a `supplier_product` have 0 products?
> 7. A product can have only one `supplier_product` connected to it? Meaning that 2 suppliers can't sell the same product?

1 done
2 done
4 done
5 havent changed
6 new supplier doesnt have products so it is ok
7 a proudct can be connected with zero or many suppliers and 2 suppliers can sell the same product

**Comment by thetaxas2468** [comment]
> > each field is yes independent but we can create a unique together fields like username for supplier and location for the supplier that he can deliver to
> > sup 1,location a sup 1,location a (is a duplicate so we need one and only one) sup 1,location b
> 
> The supplier should have an ID as its primary key. you'll never have two suppliers with the same ID as it is auto-generated, therefor such a situation will never occur.

Supplier have his primary key as username from the extend user,the example was about the DeliveryLocation

**Comment by thetaxas2468** [comment]
> > > * User has a password but does not have a username? how?
> > > * Can a delivery really have zero-to-many items in delivery? why make a delivery with zero items?
> > > * There is no such thing as 3 fields that are only unique together. each field is independent (also please remove the small comments beneath each class, it's distracting and not clear).
> > > * I don't think there can be a `product_for_supplier` (which is really items in supplier's catalog) with 0 products, meaning each product in catalog can have one product only (one-to-one)
> > > * We kinda created the names of the classes on the spot during our meeting, please refine them.
> > 
> > 
> > 
> > 1. is it possible that client and supplier (which inherit from User who has user_name as PK) will have also user_name as PK?
> > 2. yes, each delivery id could have zero or many products that were ordered to a certain area (delivery).
> > 3. isnt composite unique key is a django feature?
> > 4. modified
> 
> 1. WDYM? they don't need to have user names, just the user entity should have it. when I last looked, I didn't see it has it.
> 2. how do zero items make sense?
> 3. Not that I know, but maybe I'll learn something new :)

1 Supplier yes need usernames,supplier is registered to the system same as userbame but each one has his UI and it will be choosed by the user_type
2 an delivery_id can be and can not be in the OrderedProduct and if it can the id can be there many times because it is FK and not unique in the table
3 it is available
example:
class MyModel(models.Model):
  field1 = models.CharField(max_length=50)
  field2 = models.CharField(max_length=50)

  class Meta:
    unique_together = ('field1', 'field2',)

**Comment by nofaralfasi** [comment]
> > 6. How can a `supplier_product` have 0 products?
> > 7. A product can have only one `supplier_product` connected to it? Meaning that 2 suppliers can't sell the same product?
> 
> 6 new supplier doesnt have products so it is ok 
7 a proudct can be connected with zero or many suppliers and 2 suppliers can sell the same product

You are right. Thanks for the clarification!

**Review by brochwerger — COMMENTED** [review]
What tool are you using to generate the diagrams ?  I suggest to commit the source files of the diagrams insted of (or at least in addition to)  the generated PNGs.

**Comment by thetaxas2468** [comment]
> What tool are you using to generate the diagrams ? I suggest to commit the source files of the diagrams insted of (or at least in addition to) the generated PNGs.

https://app.diagrams.net/, We can add that in readme or something like that but the picture of the erd is okay i think,if not what do you mean i didnt understand

**Comment by thetaxas2468** [comment]
> > 
> 
> > > What tool are you using to generate the diagrams ? I suggest to commit the source files of the diagrams insted of (or at least in addition to) the generated PNGs.
> > 
> > 
> > https://app.diagrams.net/, We can add that in readme or something like that but the picture of the erd is okay i think,if not what do you mean i didnt understand
> 
> In the case of this tool, I meant the .drawio files. As any other source file they belong in the git repository so you can track changes, and let others make changes directly on the diagram. In this case the PNG files are the equivalent of the other binary files you generate for the project but don't keep in git (.pyc for compiled python, or the .vmdk image for the VirtualBox)

We dont want people to change it,idk where is the option to get .dawio files all i see html,png,jpeg ... ,the change can happend because we all share the same diagram by the link

**Comment by brochwerger** [comment]
> 

But you don't keep track of changes thru the link. Please note that diagrams.net supports saving and loading files from github. Having the PNGs in the repository is equivalent to keeping compiled code in there - not as useful as source.

**Comment by thetaxas2468** [comment]
> > 
> 
> But you don't keep track of changes thru the link. Please note that diagrams.net supports saving and loading files from github. Having the PNGs in the repository is equivalent to keeping compiled code in there - not as useful as source.

Now i understand,Done!

**Comment by Omeramsc** [comment]
1. I know you had a discussion about it earlier, but the `User` entity does not need to hold a `type`. the logic around the type will be done in code, and all information can be obtained using queries. 
2. `Supplier` and `Client` does not need a `user_name`, as the `User` entity has it. replace it with an auto generated `supplier_id` and `client_id`. 
3. Supplier could also use a `buisness_name` as I guess it is not using the `User` first and last name.

**Comment by pazMenachem** [comment]
> 1. I know you had a discussion about it earlier, but the `User` entity does not need to hold a `type`. the logic around the type will be done in code, and all information can be obtained using queries.
> 2. `Supplier` and `Client` does not need a `user_name`, as the `User` entity has it. replace it with an auto generated `supplier_id` and `client_id`.
> 3. Supplier could also use a `buisness_name` as I guess it is not using the `User` first and last name.

1. wondering how it will be done, if we would like all suppliers or clients, wouldnt it be simple to filter by user_type? 
2. will do.
3. i dont see why supplier wont use first and last name, maybe just to keep info on the supplier.
as i see it buisness name could be he's user name.

**Comment by pazMenachem** [comment]
change PR title to "Add ERD for our app".

**Comment by Omeramsc** [comment]
> > 1. I know you had a discussion about it earlier, but the `User` entity does not need to hold a `type`. the logic around the type will be done in code, and all information can be obtained using queries.
> > 2. `Supplier` and `Client` does not need a `user_name`, as the `User` entity has it. replace it with an auto generated `supplier_id` and `client_id`.
> > 3. Supplier could also use a `buisness_name` as I guess it is not using the `User` first and last name.
> 
> 1. wondering how it will be done, if we would like all suppliers or clients, wouldnt it be simple to filter by user_type?
> 2. will do.
> 3. i dont see why supplier wont use first and last name, maybe just to keep info on the supplier.
>    as i see it buisness name could be he's user name.

1. No, as you'll have a table of Suppliers. you could just request all the suppliers in that case. 
3. He can use it as metadata, but same as Apple not using 'Steve Jobs' as its name, most suppliers will have a business name. user names will usually have conventions, such as special letters or Capital\lower letters. I want to use "Red Hat", not "red_hat_01" :)

**Comment by pazMenachem** [comment]
> > > 1. I know you had a discussion about it earlier, but the `User` entity does not need to hold a `type`. the logic around the type will be done in code, and all information can be obtained using queries.
> > > 2. `Supplier` and `Client` does not need a `user_name`, as the `User` entity has it. replace it with an auto generated `supplier_id` and `client_id`.
> > > 3. Supplier could also use a `buisness_name` as I guess it is not using the `User` first and last name.
> > 
> > 
> > 
> > 1. wondering how it will be done, if we would like all suppliers or clients, wouldnt it be simple to filter by user_type?
> > 2. will do.
> > 3. i dont see why supplier wont use first and last name, maybe just to keep info on the supplier.
> >    as i see it buisness name could be he's user name.
> 
> 1. No, as you'll have a table of Suppliers. you could just request all the suppliers in that case.
> 2. He can use it as metadata, but same as Apple not using 'Steve Jobs' as its name, most suppliers will have a business name. user names will usually have conventions, such as special letters or Capital\lower letters. I want to use "Red Hat", not "red_hat_01" :)

legit.

**Comment by Omeramsc** [comment]
As mentioned before, add a supplier_id to the supplier and a client_id to the client. those will have different tables, and they need their PK.

**Comment by thetaxas2468** [comment]
> As mentioned before, add a supplier_id to the supplier and a client_id to the client. those will have different tables, and they need their PK.

They extends the User username primary key unless we override it with supplier_id or client_id

**Comment by pazMenachem** [comment]
Since i took part and maintaining this file, it looks good to me, ill join karam side for the issue of the supplier/client id.
we do have user name as PK, why would we need to override it?

**Review by pazMenachem — APPROVED** [review]
Since i took part and maintaining this file, it looks good to me, ill join karam side for the issue of the supplier/client id.
we do have user name as PK, why would we need to override it?

**Comment by Omeramsc** [comment]
@pazMenachem @thetaxas2468 Personally, I think it'll make your life easier. 
however, you can follow [this convention](https://docs.djangoproject.com/en/4.1/topics/db/models/#abstract-base-classes) if you'd like to keep it that way.

**Comment by thetaxas2468** [comment]
I thought that having supid and clientid is easier,i thibk i qill change it back like what you have said@Omeramsc

**Comment by thetaxas2468** [comment]
@pazMenachem @LiorSilberman should i change it to what omer have said and do it in the next demo i guess or what do you think?

> @pazMenachem @thetaxas2468 Personally, I think it'll make your life easier. however, you can follow [this convention](https://docs.djangoproject.com/en/4.1/topics/db/models/#abstract-base-classes) if you'd like to keep it that way.

**Pull request merged**
