### PR TITLE
Fix product module

### LINKED ISSUE #36: TEST_DATA defined twice
I (@yftacherzog) asked for TEST_DATA to be reused between the tests and the migration files, and @thetaxas2468 did that, defining the TEST_DATA inside the tests, which @Omeramsc later said should not be done.

I still wouldn't like it to be defined twice, as it makes the tests more fragile given the coupling between the migration data and the tests content. I also agree that it should be defined in the migration file.

If no objections, I think the proper way to have it is to define it on the migration files, and then import it on the tests. Generally speaking, we prefer having the tests import constants coming from the code being tested rather than the other way around.

### LINKED ISSUE #37: Use specific exception on delete_product
`delete_product` is using broad exception (`except Exception`). This will make us ignore all failures there, which is seldom what we're after.

The exception needs to change so we ignore only the specific exception that is raised when we try to delete a non-existing element.

### PR DESCRIPTION
**Pull request by thetaxas2468**
In this commit i am fixing the issues that relate
to the product module.
- fixed #37 
- fixed #36

### CODE REVIEW

**Comment by thetaxas2468** [comment]
- Fixed #37
- Fixed #36 (Can not import something like 0002_test in python or have variable like that so this thing can not be done so i created a file for constants for migration tests and pytest tests)

**Comment by yftacherzog** [comment]
@thetaxas2468 make it a point to have a single PR fix a single issue. The smaller we make a PR, the easier is to get it reviewed and merged.

**Comment by thetaxas2468** [comment]
> 

how to to do pr for each one since i am up to date to the last version and both of the issues are updated

**Comment by yftacherzog** [comment]
> > 
> 
> how to to do pr for each one since i am up to date to the last version and both of the issues are updated

They are two separate issues on the same file.
So, in this case, you base them both on upstream/main as it is now, and if when the first one is merged, you get conflicts on the one still unmerged, then you rebase it.

**Comment by Omeramsc** [comment]
1. Don't link issues in comments, link them in the description of the PR. If after linking an issue it doesn't appear under the development section on the right side of the window, it wasn't done the right way.
image
2. PLEASE, be more informative in the description! which issues? what problem did they cause? how are they being fixed? any extra information?

**Comment by thetaxas2468** [comment]
> Also, imagine that we need to roll back a PR. It will be very unfortunate if fixing a regression will require rolling back an unrelated fix/feature.

Done

**Comment by thetaxas2468** [comment]
> 1. Don't link issues in comments, link them in the description of the PR. If after linking an issue it doesn't appear under the development section on the right side of the window, it wasn't done the right way.
>    image
> 2. PLEASE, be more informative in the description! which issues? what problem did they cause? how are they being fixed? any extra information?

Done

**Pull request closed without merging**
