### PR TITLE
Add pytest to our github

### PR DESCRIPTION
**Pull request by thetaxas2468**
Adding pytest to be available to run the tests and provide us with details about the tests with each PR that has tests.

### CODE REVIEW

**Comment by yftacherzog** [comment]
@thetaxas2468 change the commit message title and the PR name so it conforms with the convention mentioned on the contributing guide. Specifically, use `add` instead of `adding` (it should sound like you're telling someone to do it).

**Comment by pazMenachem** [comment]
other than the title, it does looks ok to merge

**Comment by Omeramsc** [comment]
Please conform to the contribution guide: 
- link an issue
- add reviewers and assignee
- as mentioned, fix the title. 

other than that, LGTM

**Comment by pazMenachem** [comment]
> Please conform to the contribution guide:
> 
>  link an issue


> When reviewing, confirm that the code accomplishes the requirements and the acceptance criteria by using one or both ways: A GitHub issue: the code fixes the problem. Adding a feature: elaborate in the commit the purpose of the code. Both cases should have accompanying unit tests that cover all the relevant edge cases.

just to verify, this PR doesnt count as adding a feature? why linking to an issue?

**Comment by LiorSilberman** [comment]
I dont see somthing wrong in the files exept what Paz said about the title.
I think it can be merge

**Comment by thetaxas2468** [comment]
#29

**Comment by Omeramsc** [comment]
> > Please conform to the contribution guide:
> > link an issue
> 
> > When reviewing, confirm that the code accomplishes the requirements and the acceptance criteria by using one or both ways: A GitHub issue: the code fixes the problem. Adding a feature: elaborate in the commit the purpose of the code. Both cases should have accompanying unit tests that cover all the relevant edge cases.
> 
> just to verify, this PR doesnt count as adding a feature? why linking to an issue?

TBH I didn't notice the way it was phrased in the contribution guide and would highly suggest changing it. 
an issue does not have to be a "problem" or a "bug", it can also be a feature request. an issue linked to any kind of PR adds clarity and makes it easy to follow the reasons for the change and who is involved.

**Pull request merged**
